from pygame.locals import *
from pygame.event import Event

from entities.ui.text import Text
from entities.bases import Base
from entities.floors import Crack, Border
from entities.walls import Wall
from entities.doors import IronDoubleDoor, GoldenDoubleDoor

from mixins.managed import Managed
from mixins.container import Container

from utils.colors import LIGHT

class LevelScreen(Managed, Container):
    """Level Screen class."""

    def __init__(self) -> None:
        Managed.__init__(self)
        Container.__init__(self)
        self.entities = [
            Base("dark").with_position(0, 0),
            Base("dark").with_position(1, 0),
            Base("dark").with_position(2, 0),
            Base("dark").with_position(3, 0),
            Base("dark").with_position(4, 0),
            Base("dark").with_position(5, 0),
            Base("dark").with_position(6, 0),
            Base("dark").with_position(7, 0),
            Base("dark").with_position(8, 0),
            Base("dark").with_position(9, 0),
            Base("dark").with_position(10, 0),
            Base("dark").with_position(11, 0),
            Base("dark").with_position(12, 0),
            Base("dark").with_position(13, 0),
            Base("dark").with_position(14, 0),
            Base("dark").with_position(15, 0),
            Base("dark").with_position(16, 0),
            Base("dark").with_position(17, 0),
            Base("dark").with_position(18, 0),
            Base("dark").with_position(19, 0),
            Base("dark").with_position(0, 1),
            Base("dark").with_position(1, 1),
            Base("dark").with_position(2, 1),
            Base("dark").with_position(3, 1),
            Base("dark").with_position(4, 1),
            Base("dark").with_position(5, 1),
            Base("dark").with_position(6, 1),
            Base("dark").with_position(7, 1),
            Base("dark").with_position(8, 1),
            Base("dark").with_position(9, 1),
            Base("dark").with_position(10, 1),
            Base("dark").with_position(11, 1),
            Base("dark").with_position(12, 1),
            Base("dark").with_position(13, 1),
            Base("dark").with_position(14, 1),
            Base("dark").with_position(15, 1),
            Base("dark").with_position(16, 1),
            Base("dark").with_position(17, 1),
            Base("dark").with_position(18, 1),
            Base("dark").with_position(19, 1),
            Base("dark").with_position(0, 2),
            Base("dark").with_position(1, 2),
            Base("dark").with_position(2, 2),
            Base("dark").with_position(3, 2),
            Base("dark").with_position(4, 2),
            Base("dark").with_position(5, 2),
            Base("dark").with_position(6, 2),
            Base("dark").with_position(7, 2),
            Base("dark").with_position(8, 2),
            Base("dark").with_position(9, 2),
            Base("dark").with_position(10, 2),
            Base("dark").with_position(11, 2),
            Base("dark").with_position(12, 2),
            Base("dark").with_position(13, 2),
            Base("dark").with_position(14, 2),
            Base("dark").with_position(15, 2),
            Base("dark").with_position(16, 2),
            Base("dark").with_position(17, 2),
            Base("dark").with_position(18, 2),
            Base("dark").with_position(19, 2),
            Base("dark").with_position(0, 3),
            Base("dark").with_position(1, 3),
            Base("medium").with_position(2, 3),
            Base("medium").with_position(3, 3),
            Base("medium").with_position(4, 3),
            Base("medium").with_position(5, 3),
            Base("medium").with_position(6, 3),
            Base("medium").with_position(7, 3),
            Base("medium").with_position(8, 3),
            Base("medium").with_position(9, 3),
            Base("medium").with_position(10, 3),
            Base("medium").with_position(11, 3),
            Base("medium").with_position(12, 3),
            Base("medium").with_position(13, 3),
            Base("medium").with_position(14, 3),
            Base("medium").with_position(15, 3),
            Base("medium").with_position(16, 3),
            Base("medium").with_position(17, 3),
            Base("dark").with_position(18, 3),
            Base("dark").with_position(19, 3),
            Base("dark").with_position(0, 4),
            Base("dark").with_position(1, 4),
            Base("medium").with_position(2, 4),
            Base("medium").with_position(3, 4),
            Base("medium").with_position(4, 4),
            Base("medium").with_position(5, 4),
            Base("medium").with_position(6, 4),
            Base("medium").with_position(7, 4),
            Base("medium").with_position(8, 4),
            Base("medium").with_position(9, 4),
            Base("medium").with_position(10, 4),
            Base("medium").with_position(11, 4),
            Base("medium").with_position(12, 4),
            Base("medium").with_position(13, 4),
            Base("medium").with_position(14, 4),
            Base("medium").with_position(15, 4),
            Base("medium").with_position(16, 4),
            Base("medium").with_position(17, 4),
            Base("dark").with_position(18, 4),
            Base("dark").with_position(19, 4),
            Base("dark").with_position(0, 5),
            Base("dark").with_position(1, 5),
            Base("medium").with_position(2, 5),
            Base("medium").with_position(3, 5),
            Base("medium").with_position(4, 5),
            Base("medium").with_position(5, 5),
            Base("medium").with_position(6, 5),
            Base("medium").with_position(7, 5),
            Base("medium").with_position(8, 5),
            Base("medium").with_position(9, 5),
            Base("medium").with_position(10, 5),
            Base("medium").with_position(11, 5),
            Base("medium").with_position(12, 5),
            Base("medium").with_position(13, 5),
            Base("medium").with_position(14, 5),
            Base("medium").with_position(15, 5),
            Base("medium").with_position(16, 5),
            Base("medium").with_position(17, 5),
            Base("dark").with_position(18, 5),
            Base("dark").with_position(19, 5),
            Base("dark").with_position(0, 6),
            Base("dark").with_position(1, 6),
            Base("medium").with_position(2, 6),
            Base("medium").with_position(3, 6),
            Base("medium").with_position(4, 6),
            Base("medium").with_position(5, 6),
            Base("medium").with_position(6, 6),
            Base("medium").with_position(7, 6),
            Base("medium").with_position(8, 6),
            Base("medium").with_position(9, 6),
            Base("medium").with_position(10, 6),
            Base("medium").with_position(11, 6),
            Base("medium").with_position(12, 6),
            Base("medium").with_position(13, 6),
            Base("medium").with_position(14, 6),
            Base("medium").with_position(15, 6),
            Base("medium").with_position(16, 6),
            Base("medium").with_position(17, 6),
            Base("dark").with_position(18, 6),
            Base("dark").with_position(19, 6),
            Base("dark").with_position(0, 7),
            Base("dark").with_position(1, 7),
            Base("medium").with_position(2, 7),
            Base("medium").with_position(3, 7),
            Base("medium").with_position(4, 7),
            Base("medium").with_position(5, 7),
            Base("medium").with_position(6, 7),
            Base("medium").with_position(7, 7),
            Base("medium").with_position(8, 7),
            Base("medium").with_position(9, 7),
            Base("medium").with_position(10, 7),
            Base("medium").with_position(11, 7),
            Base("medium").with_position(12, 7),
            Base("medium").with_position(13, 7),
            Base("medium").with_position(14, 7),
            Base("medium").with_position(15, 7),
            Base("medium").with_position(16, 7),
            Base("medium").with_position(17, 7),
            Base("dark").with_position(18, 7),
            Base("dark").with_position(19, 7),
            Base("dark").with_position(0, 8),
            Base("dark").with_position(1, 8),
            Base("medium").with_position(2, 8),
            Base("medium").with_position(3, 8),
            Base("medium").with_position(4, 8),
            Base("medium").with_position(5, 8),
            Base("medium").with_position(6, 8),
            Base("medium").with_position(7, 8),
            Base("medium").with_position(8, 8),
            Base("medium").with_position(9, 8),
            Base("medium").with_position(10, 8),
            Base("medium").with_position(11, 8),
            Base("medium").with_position(12, 8),
            Base("medium").with_position(13, 8),
            Base("medium").with_position(14, 8),
            Base("medium").with_position(15, 8),
            Base("medium").with_position(16, 8),
            Base("medium").with_position(17, 8),
            Base("dark").with_position(18, 8),
            Base("dark").with_position(19, 8),
            Base("dark").with_position(0, 9),
            Base("dark").with_position(1, 9),
            Base("medium").with_position(2, 9),
            Base("medium").with_position(3, 9),
            Base("medium").with_position(4, 9),
            Base("medium").with_position(5, 9),
            Base("medium").with_position(6, 9),
            Base("medium").with_position(7, 9),
            Base("medium").with_position(8, 9),
            Base("medium").with_position(9, 9),
            Base("medium").with_position(10, 9),
            Base("medium").with_position(11, 9),
            Base("medium").with_position(12, 9),
            Base("medium").with_position(13, 9),
            Base("medium").with_position(14, 9),
            Base("medium").with_position(15, 9),
            Base("medium").with_position(16, 9),
            Base("medium").with_position(17, 9),
            Base("dark").with_position(18, 9),
            Base("dark").with_position(19, 9),
            Base("dark").with_position(0, 10),
            Base("dark").with_position(1, 10),
            Base("dark").with_position(2, 10),
            Base("dark").with_position(3, 10),
            Base("medium").with_position(4, 10),
            Base("medium").with_position(5, 10),
            Base("dark").with_position(6, 10),
            Base("dark").with_position(7, 10),
            Base("dark").with_position(8, 10),
            Base("dark").with_position(9, 10),
            Base("dark").with_position(10, 10),
            Base("dark").with_position(11, 10),
            Base("dark").with_position(12, 10),
            Base("dark").with_position(13, 10),
            Base("dark").with_position(14, 10),
            Base("dark").with_position(15, 10),
            Base("dark").with_position(16, 10),
            Base("dark").with_position(17, 10),
            Base("dark").with_position(18, 10),
            Base("dark").with_position(19, 10),
            Base("dark").with_position(0, 11),
            Base("dark").with_position(1, 11),
            Base("dark").with_position(2, 11),
            Base("dark").with_position(3, 11),
            Base("dark").with_position(4, 11),
            Base("dark").with_position(5, 11),
            Base("dark").with_position(6, 11),
            Base("dark").with_position(7, 11),
            Base("dark").with_position(8, 11),
            Base("dark").with_position(9, 11),
            Base("dark").with_position(10, 11),
            Base("dark").with_position(11, 11),
            Base("dark").with_position(12, 11),
            Base("dark").with_position(13, 11),
            Base("dark").with_position(14, 11),
            Base("dark").with_position(15, 11),
            Base("dark").with_position(16, 11),
            Base("dark").with_position(17, 11),
            Base("dark").with_position(18, 11),
            Base("dark").with_position(19, 11),
            Wall("vertical_0").with_position(1, 2),
            Wall("vertical_1").with_position(1, 3),
            Wall("vertical_0").with_position(1, 4),
            Wall("vertical_0").with_position(1, 5),
            Wall("vertical_1").with_position(1, 6),
            Wall("vertical_1").with_position(1, 7),
            Wall("vertical_0").with_position(1, 8),
            Wall("vertical_1").with_position(1, 9),
            Wall("corner_1").with_position(1, 10),
            Wall("horizontal_0").with_position(2, 2),
            Wall("horizontal_2").with_position(3, 2),
            Wall("horizontal_0").with_position(4, 2),
            Wall("horizontal_4").with_position(5, 2),
            Wall("horizontal_1").with_position(6, 2),
            Wall("horizontal_5").with_position(7, 2),
            Wall("horizontal_3").with_position(8, 2),
            IronDoubleDoor("closed").with_position(9, 2),
            Wall("horizontal_2").with_position(11, 2),
            Wall("horizontal_1").with_position(12, 2),
            Wall("horizontal_3").with_position(13, 2),
            Wall("horizontal_2").with_position(14, 2),
            Wall("horizontal_2").with_position(15, 2),
            Wall("horizontal_5").with_position(16, 2),
            Wall("horizontal_4").with_position(17, 2),
            Wall("vertical_0").with_position(18, 2).with_flipped(True, False),
            Wall("vertical_1").with_position(18, 3).with_flipped(True, False),
            Wall("vertical_0").with_position(18, 4).with_flipped(True, False),
            Wall("vertical_0").with_position(18, 5).with_flipped(True, False),
            Wall("vertical_1").with_position(18, 6).with_flipped(True, False),
            Wall("vertical_1").with_position(18, 7).with_flipped(True, False),
            Wall("vertical_0").with_position(18, 8).with_flipped(True, False),
            Wall("vertical_1").with_position(18, 9).with_flipped(True, False),
            Wall("corner_1").with_position(18, 10).with_flipped(True, False),
            Wall("horizontal_6").with_position(2, 10),
            Wall("corner_0").with_position(3, 10).with_flipped(True, False),
            GoldenDoubleDoor("closed").with_position(4, 10),
            Wall("corner_0").with_position(6, 10),
            Wall("horizontal_9").with_position(7, 10),
            Wall("horizontal_8").with_position(8, 10),
            Wall("horizontal_7").with_position(9, 10),
            Wall("horizontal_8").with_position(10, 10),
            Wall("horizontal_9").with_position(11, 10),
            Wall("horizontal_8").with_position(12, 10),
            Wall("horizontal_9").with_position(13, 10),
            Wall("horizontal_7").with_position(14, 10),
            Wall("horizontal_8").with_position(15, 10),
            Wall("horizontal_7").with_position(16, 10),
            Wall("horizontal_9").with_position(17, 10),
            Border("2sides_perpendicular").with_position(2, 3),
            Border("side").with_position(3, 3),
            Border("side").with_position(4, 3),
            Border("side").with_position(5, 3),
            Border("side").with_position(6, 3),
            Border("side").with_position(7, 3),
            Border("side").with_position(8, 3),
            Border("side").with_position(9, 3),
            Border("side").with_position(10, 3),
            Border("side").with_position(11, 3),
            Border("side").with_position(12, 3),
            Border("side").with_position(13, 3),
            Border("side").with_position(14, 3),
            Border("side").with_position(15, 3),
            Border("side").with_position(16, 3),
            Border("side").with_position(17, 3),
            Border("2sides_perpendicular").with_position(17, 3).with_flipped(True, False),
            Border("2sides_perpendicular").with_position(2, 9).with_flipped(False, True),
            Border("2sides_perpendicular").with_position(17, 9).with_flipped(True, True),
            Text("level_screen_title", 60, LIGHT).with_position(100, 50)
        ]
        self.controllable = self.entities[0]

    def on_event(self, event: Event) -> None:
        """Catch events for the Level Screen."""
        if event.type == KEYDOWN:
            if event.key == K_ESCAPE:
                self.manager.changeScreen("start")
            elif event.key == K_a:
                self.controllable.x -= 1
                self.controllable.x_flipped = True
            elif event.key == K_d:
                self.controllable.x += 1
                self.controllable.x_flipped = False
            elif event.key == K_w:
                self.controllable.y -= 1
            elif event.key == K_s:
                self.controllable.y += 1
        Container.on_event(self, event)